query Posts {
    articles {
        data {
            id
            attributes {
                title
                content
                createdAt
                description
                category {
                    data {
                        id
                        attributes {
                            createdAt
                            name
                            articles {
                                data {
                                    attributes {
                                        title
                                        slug
                                    }
                                }
                            }
                            createdAt
                        }
                    }
                }
            }
        }
    }
}
